baseURL: https://louisfrach.netlify.app/
languageCode: en-us
title: Tennis, Data Analytics, and Me
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Start exploring
    subtitle: Keep scrolling to find out how these three seemingly unrelated things are connected and find out more about me along the way.
    title: Tennis, Data Analytics, and Me 
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: London Business School Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lfrach.mfa2022@london.edu
        title: Personal Email
    enable: yes
    phone:
      - phone: 020 7000 7000
        title: London Business School Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Louis DataCo
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/LondonBusinessSchool/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/londonbschool/
      - icon: fa-github
        label: GitHub
        url: https://github.com/lfrach
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/louis-frach-5a9741142/
  image: ""
  name: Your name
  navigation:
    button1:
      - name: Find me at LBS
        url: https://www.google.de/maps/place/London+Business+School/@51.5261552,-0.1628567,17z/data=!3m1!4b1!4m5!3m4!1s0x48761ac6309dd51b:0xbf9c52f1c02b7723!8m2!3d51.5261552!4d-0.160668
    button2:
      - name: LinkedIn
        url: https://www.linkedin.com/in/louis-frach/
    links:
      - name: Home
        url: '#'
      - name: Blog Overview
        url: blogs
      - name: Meme Gallery
        url: blogs/pictures
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: person.jpg
        subtitle: What you need to know to get started
        title: About me
        url: blogs/intro
      - image: collage.jpg
        subtitle: How this website connects two unrelated disciplines
        title: Tennis and data analytics
        url: blogs/data_and_tennis
      - image: tennis_practice.jpg
        subtitle: Both disciplines require rigorous training
        title: 1. Practice
        url: blogs/practice
      - image: coding_1.jpg
        subtitle: Data analytics as well as tennis rely on a strong technical foundation
        title: 2. Technical Finesse
        url: blogs/technical_finesse
      - image: teamwork.jpg
        subtitle: Nothing amplifies success more than working in teams
        title: 3. Teamwork
        url: blogs/teamwork
      - image: success.jpg
        subtitle: There's nothing like winning a trophy or cracking the code
        title: 4. Success
        url: blogs/success

  two:
    buttonText: Connect here
    enable: yes
    subtitle: I hope that this website has given you some insights on me as a person and how two seemingly unrelated disciplines are actually quite similar. Should you share some of the same values that I have described throughout this site, feel free to connect with me on LinkedIn! I am looking forward to hearing from you.
    title: Next steps
    url: https://www.linkedin.com/in/louis-frach-5a9741142/
