baseURL: https://louisfrach.netlify.app/
languageCode: en-us
title: Tennis, Data Analytics, and Me
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Start exploring
    subtitle: An introduction to me and why I believe that tennis and data analytics have similar ingredients to success. 
    Scroll down to discover what dimensions define the two disciplines and find out where I see my strengths and weaknesses. 
    title: Tennis, Data Analytics, and Me 
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: London Business School Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lfrach.mfa2022@london.edu
        title: Personal Email
    enable: yes
    phone:
      - phone: 020 7000 7000
        title: London Business School Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Louis DataCo
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/LondonBusinessSchool/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/londonbschool/
      - icon: fa-github
        label: GitHub
        url: https://github.com/lfrach
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/louis-frach-5a9741142/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: person.jpg
        subtitle: What you need to know to get started
        title: About me
        url: blogs/aliquam
      - image: collage.jpg
        subtitle: How this website connects two unrelated disciplines
        title: About tennis and data analytics
        url: blogs/ipsum
      - image: tennis_practice.jpg
        subtitle: Both disciplines require rigorous training
        title: Practice
        url: blogs/aliquam
      - image: coding_1.jpg
        subtitle: Data analytics as well as tennis rely on a strong technical foundation
        title: Technical Finesse
        url: blogs/tempus
      - image: teamwork.jpg
        subtitle: Nothing amplifies success more than working in teams
        title: Teamwork
        url: blogs/magna
      - image: failure.jpg
        subtitle: Mistakes, failure, and losses are part of the game
        title: Failure
        url: blogs/ipsum

  two:
    buttonText: Connect here
    enable: yes
    subtitle: I hope that this website has given you some insights on me as a person and how two seemingly 
    unrelated disciplines are actually quite similar. Should you share some of the same values that 
    I have described throughout this site, feel free to connect with me on LinkedIn! I am looking forward 
    to hearing from you.
    title: Next steps
    url: blogs
